parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    useJSXTextNode: true
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json

extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - "plugin:react/jsx-runtime"

rules:
  no-console: off
  no-unused-vars: 'off'
  linebreak-style: 'off'
  react/react-in-jsx-scope: off
  react/jsx-curly-brace-presence:
    - 'error'
    - props: 'never'
      children: 'never'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: off
  prettier/prettier:
    - error
    - endOfLine: auto
  '@typescript-eslint/no-non-null-assertion': warn
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/ban-ts-comment': warn
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true

plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier

settings:
  react:
    pragma: React
    version: detect
